# The language in this case has no bearing - we are going to be making use of conda for a
# python distribution for the scientific python stack.
language: python

sudo: false

env:
    global:
       - CONDA_INSTALL_LOCN="${HOME}/conda"
       # Doctr deploy key for SciTools/courses
       - secure: "QoIc+m9R8SRA0ARoa1Upl/loZNbex4QXQw7wHHYEVd3kZn90rshvqMcjM926d7sUrRpTMaeIKphMSDvHr34Fp9GXjEVHqtAjfNOZo146xWVd6Fcp9eYv3eHLCX/MrJytWPQkutzqCCCzXUUVpSMgWLNgZt2jhYuBTI/p7NmMmH0="

install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ${HOME}/miniconda.sh
    - bash ${HOME}/miniconda.sh -b -p ${CONDA_INSTALL_LOCN} && export PATH=${CONDA_INSTALL_LOCN}/bin:$PATH

    - git config --global user.name "Travis user"
    - git config --global user.email travis-tests@example.com

    # Now do the things we need to do to install it.
    - conda install notebook nbconvert python pip --yes --quiet
    - pip install doctr

script:
    - set -e
    - ./make.sh
    - doctr deploy ./ --deploy-branch-name build --built-docs build --key-path .github/github_deploy_key_scitools_courses.enc --branch-whitelist fix_deploy;
